image: lorisleiva/laravel-docker:7.3

definitions:
  steps:
    - step: &Install
        name: Install
        image: bitnami/laravel:6.0.2
        script:
          - npm install
          - composer install
        artifacts:
          - node_modules/**
          - vendor/**
    - step: &Build
        name: Build
        script:
          - apk add ffmpeg
          - npx audiosprite -f howler2 -o public/audio/audiosprites -u /audio resources/audio/*.wav
          - npm run prod
        artifacts:
          - public/**
          - vendor/**
    - step: &Test
        name: Test
        image: bitnami/laravel:6.0.2
        script:
          - vendor/bin/phpunit --coverage-text --colors=never
          - php artisan code:analyse --env=testing
    - step: &Deploy
        name: Deploy [Unnamed]
        script:
          - ./deploy.sh
  caches:
    node: node_modules
    composer: vendor
    public: public

pipelines:
  default:
    - step: *Install
    - step: *Build
    - step: *Test
  branches:
    release/staging:
      - step: *Install
      - step: *Build
      - step:
          <<: *Deploy
          name: Deploy to Staging
          deployment: staging
    release/production:
      - step: *Install
      - step: *Build
      - step:
          <<: *Deploy
          name: Deploy to Production
          deployment: production
