version: "3"

services:
  www:
    image: bitnami/laravel:6.0.2
    user: "1000:1000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=tag-diary
      - DB_USERNAME=tag-diary
      - DB_PASSWORD=tag-diary
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    volumes:
      - .:/app
    ports:
      - 3000:3000 # Laravel Server
      - 3001:3001 # BrowserSync UI
      - 8080:8080 # BrowserSync Server
    links:
      - redis
      - mysql
  redis:
    image: "redis"
  mysql:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=tag-diary
      - MARIADB_DATABASE=tag-diary
      - MARIADB_PASSWORD=tag-diary
